Project Artipy {
  database_type: 'PostgreSQL'
  Note: '''
    # Artipy Database
    This database contains the data collected from Spotify Web API and the Art Institute of Chicago API used to create the synesthesia dashboard. 
  '''
}
Table spotify as S {
id                   varchar [pk]
name                 varchar
preview_url          varchar
track_url            varchar
artists_names        varchar
first_artist_id      varchar
album_image          varchar
album_name           varchar
release_date         varchar
explicit               varchar
popularity          float
danceability        float
energy              float
key                 float
loudness            float
mode                float
speechiness         float
acousticness        float
instrumentalness    float
liveness            float
valence             float
tempo               float
}
Table artists as A {
genres         varchar
artist_id      varchar [pk]
artist_name    varchar

}
Table artworks as R {
id                      int [pk]
title                  varchar
medium_display         varchar
date_display           varchar
artist_info_display    varchar
place_origin           varchar
description            varchar
image_id               varchar
image_url              varchar
artwork_type           varchar
artwork_type_id         int
department_title       varchar
department_id          varchar
artist_id               int
artist_name            varchar
style_id               varchar
style_title            varchar

}

Ref: S.first_artist_id > A.artist_id  

